# Generated by Django 4.2.21 on 2025-05-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_title', models.CharField(blank=True, max_length=300, null=True)),
                ('notes_content', models.TextField()),
                ('create_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_title', models.CharField(blank=True, max_length=300, null=True)),
                ('Test_content', models.TextField()),
                ('create_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('create_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
