# Generated by Django 4.2.21 on 2025-05-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_notes_is_active_users_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
