# Generated by Django 4.2.21 on 2025-05-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0003_notes_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
