# Generated by Django 4.2.21 on 2025-05-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0004_alter_notes_create_on_alter_test_create_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
