# Generated by Django 4.2.21 on 2025-05-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0006_delete_test_alter_notes_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_password',
            field=models.CharField(blank=True, null=True),
        ),
    ]
