# Generated by Django 4.2.21 on 2025-05-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0007_users_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
