version: '3.8.2'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: notes_database
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db

volumes:
  postgres_data:
